# Generated by Django 6.0.4 on 2026-05-05 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('osca_id', models.CharField(help_text='Official OSCA ID Number', max_length=50, unique=True)),
                ('barangay', models.CharField(max_length=100)),
                ('is_indigent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('risk_score', models.FloatField(default=0.0, help_text='Anomaly risk score from Random Forest model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='Related ID (e.g., Disbursement Ref or Senior OSCA ID)', max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1 (Jan-Mar)'), ('Q2', 'Quarter 2 (Apr-Jun)'), ('Q3', 'Quarter 3 (Jul-Sep)'), ('Q4', 'Quarter 4 (Oct-Dec)')], max_length=2)),
                ('year', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='core.senior')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_reason', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(help_text='ML Confidence Score (0.0 to 1.0)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.senior')),
            ],
        ),
    ]
