# Generated by Django 6.0.4 on 2026-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_type',
            field=models.CharField(choices=[('SOCIAL_PENSION', 'DSWD Social Pension'), ('MILESTONE_GIFT', 'Centenarian/Milestone Gift')], default='SOCIAL_PENSION', max_length=20),
        ),
    ]
