# Generated by Django 6.0.4 on 2026-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='annex_a_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
