# Generated by Django 6.0.4 on 2026-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_senior_annex_a_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended/Fraud')], default='ACTIVE', max_length=20),
        ),
    ]
