# Generated by Django 6.0.4 on 2026-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_senior_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='picture_2x2_file',
            field=models.ImageField(blank=True, null=True, upload_to='requirements/pictures/'),
        ),
        migrations.AddField(
            model_name='senior',
            name='primary_id_file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/id/'),
        ),
        migrations.AddField(
            model_name='senior',
            name='psa_cert_file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/psa/'),
        ),
    ]
