# Generated by Django 6.0.4 on 2026-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_senior_picture_2x2_file_senior_primary_id_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='status',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
