# Generated by Django 6.0.4 on 2026-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_status_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='civil_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='senior',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
