# Generated by Django 6.0.4 on 2026-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_senior_civil_status_senior_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='is_indigent',
            field=models.BooleanField(default=True),
        ),
    ]
