# Generated by Django 6.0.4 on 2026-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_senior_auto_check_results_senior_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='civil_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=20),
        ),
    ]
