# Generated by Django 6.0.4 on 2026-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_senior_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='picture_2x2_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='senior',
            name='primary_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='senior',
            name='psa_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
