# Generated by Django 6.0.4 on 2026-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_senior_picture_2x2_hash_senior_primary_id_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Official date of death recorded by civil registry', null=True),
        ),
        migrations.AddField(
            model_name='senior',
            name='death_cert_file',
            field=models.FileField(blank=True, help_text='Scanned PSA Death Certificate', null=True, upload_to='requirements/death_certs/'),
        ),
    ]
