# Generated by Django 6.0.4 on 2026-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_senior_date_of_death_senior_death_cert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='senior',
            name='barangay',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='senior',
            name='date_of_birth',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='registration_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Correction')], db_index=True, default='PENDING_REVIEW', help_text='Document verification status in the review pipeline', max_length=20),
        ),
        migrations.AlterField(
            model_name='senior',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='senior',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended/Fraud')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
